config:
  clientID: "oauth2-proxy"
  clientSecret: "jlfa14HlYOmqeAdXZyfMSWl50Fd96pkf"
  cookieSecret: "NXA4K2lMUGsrSnFLYnprWnZESE5GUDNINzIrc2NHUnQ="
  configFile: |-
    provider = "oidc"
    provider_display_name = "Keycloak"
    oidc_issuer_url = "https://sso.k8s.sikademo.com/realms/example"
    email_domains = [ "sikademo.com", "ondrejsika.com" ]
    scope = "openid profile email"
    cookie_domains = ".k8s.sikademo.com"
    whitelist_domains = ".k8s.sikademo.com"
    pass_authorization_header = true
    pass_access_token = true
    pass_user_headers = true
    set_authorization_header = true
    set_xauthrequest = true
    cookie_refresh = "1m"
    cookie_expire = "30m"

ingress:
  enabled: true
  path: /
  hosts:
    - oauth.k8s.sikademo.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  tls:
    - secretName: oauth-proxy-tls
      hosts:
        - oauth.k8s.sikademo.com
