---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: example-secret-1
  namespace: default
spec:
  encryptedData:
    foo: AgCet3VdcWLGs9mbhfWJPJjm7SHTr8ifsKmZP1BjZiWnjizGCtR8JqTsaIrLC9OdLMhW0x+AyMbhC7l+1aa8SXhjD2DKejuDO/KfBYmeJMzQcF+iSlq5eJqpHvqsXoXUWzmQ3tkOa2uSrVioEg3ePokBDng/A3tHU4/oDyNLhH5XARGNKzGpTfRt8tC+ORTvKjzpomoQm4pESLopf9ctQXYu8hIYQobhUhScYjp4JlxDR9sRZzXBeRTeoHJNZxB0WNXxha8UTfG/TqQzq1hkrsMd5JfjuxewQnOCbdVq4+Rd+HkqbO+BPu/JFzztY7ZZNV2aLXFcFg4yjuD/1MLdrO2yhAmHZoVHA/CvnYV/YLlzAFZkOP00FwD0RB1lbBnYzsFuNkh6TUPLLWwd6EVATN/6p7KxDjvXUr9jwEeHVPBg/ARviyWQ9Fe/N7APutmX/uoMUFxOwELrI2fTzzjfcsYSNPdtQP7qP4fsCufqQ6y7/7VhKnz0QhHBW1uX5tUR9U9t6ruSFzglo1KeEcocuey4zZGzA4kop84MKU0doNLqI+dnP1O0LQwymORENbJgZ/gEQJjkZTK2U5CFHksqGJbk2AgAvUcOleYU/YFcybBuRIwVWfBA2VNRONabgdLvOD1HwlbVfIT0wvq8dDRny24nu1DnQycpZsXlzNiXXOaVmwzIpBBWllZ4VVGXleo9oCukZ1E=
  template:
    metadata:
      creationTimestamp: null
      name: example-secret-1
      namespace: default
